// <auto-generated />
using System;
using ChildCareDAL.DBcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChildCareDAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("Varchar(30)");

                    b.Property<string>("UserImage")
                        .HasMaxLength(245)
                        .HasColumnType("Varchar(245)");

                    b.Property<int>("parentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("childTable");
                });

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.ChildEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdmissionStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Admission_Approveby")
                        .HasColumnType("longtext");

                    b.Property<string>("Classname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreateBy")
                        .HasColumnType("longtext");

                    b.Property<string>("CreateDate")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EnrollmentEndinggDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EnrollmentStartingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slotname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdateDate")
                        .HasColumnType("longtext");

                    b.Property<int>("childID")
                        .HasColumnType("int");

                    b.Property<int>("parentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("childEntrollmentTable");
                });

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.ClassList", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ClassId");

                    b.ToTable("classListTable");
                });

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.FileDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("FileDetails");
                });

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("Varchar(70)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("Varchar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("Varchar(70)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("Varchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("Varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("Varchar(30)");

                    b.Property<string>("UserImage")
                        .HasColumnType("Varchar");

                    b.Property<string>("loginname")
                        .IsRequired()
                        .HasColumnType("Varchar");

                    b.HasKey("Id");

                    b.ToTable("parentTable");
                });

            modelBuilder.Entity("businessServicess.models.RequestModels.ChildCare.SlotList", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SlotId");

                    b.ToTable("slotListTable");
                });
#pragma warning restore 612, 618
        }
    }
}
